# Generated by Django 3.1.5 on 2021-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
